name: Translation Request
description: Request a translation of our project into another language
title: "Translation Request"
body:
  - type: markdown
    attributes:
      value: |
        ## Translation Request

        Please fill out the following information to request a translation of our project into another language.

  - type: dropdown
    id: language
    attributes:
      label: Language
      description: "Please select the language you would like the project to be translated into:"
      options:
        - "Spanish"
        - "French"
        - "German"
        - "Italian"
        - "Other"

  - type: input
    id: url
    attributes:
      label: Page URL
      description: "If you have a page that needs to be translated, please provide a url:"

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information (Optional)
      description: "If you have any additional information or special requests for the translation, please describe them here:"
      placeholder: "Type your additional information here..."
